Add failing test for ignoring hyphen in word boundaries
duereg/too-wordy pull request #4
Opened 2019-11-17 22:05 UTC by HonzaMac

Adding failing tests for issue https://github.com/btford/write-good/issues/112

2019-11-18 14:26 UTC, RichardLitt requested changes

2019-11-18 14:26 UTC, RichardLitt commented on test/basic.spec.js
> +  describe('a sentence with hyphen should parse word as one', () => {
Should be rephrased: "hyphenated words should not be parsed as two words". I think this is more clear.

2019-11-25 14:30 UTC, RichardLitt commented
Thanks, @HonzaMac. LGTM.

2021-01-26 02:52 UTC, RichardLitt commented
@duereg Any reason this wasn't merged?

2021-01-26 09:01 UTC, HonzaMac commented
There was only failing test, but no actual fix. 
There was no action for more then 1 year.

2021-01-26 10:08 UTC, HonzaMac commented
@RichardLitt I've made fix, please review.

2021-01-26 12:51 UTC, RichardLitt commented
My review isn't worth much. I'm not the maintainer.

2021-01-26 17:58 UTC, HonzaMac commented
@duereg Please, can you take a look?

2021-02-01 19:40 UTC, merged

2021-02-01 19:56 UTC, duereg commented
bumped to 0.3.0. Thanks!

2021-02-01 20:13 UTC, HonzaMac commented
Tahnk you!